Traceback (most recent call last):
  File "root.py", line 16, in <module>
    db = Connection().pspct
  File "build/bdist.macosx-10.7-intel/egg/pymongo/connection.py", line 381, in __init__
  File "build/bdist.macosx-10.7-intel/egg/pymongo/connection.py", line 659, in __find_node
pymongo.errors.AutoReconnect: could not connect to localhost:27017: [Errno 61] Connection refused
